#!/bin/bash

for filename in $*; do
  outfile=`basename $filename`.hs
  case ${filename} in
    README.md) cat - >$outfile <<EOF
import qualified Data.Text.IO

readData = Data.Text.IO.readFile "$filename"

main = readData >>= print
EOF
;;
    Prestige.csv) cat -  >$outfile<<EOF
{-# LANGUAGE DataKinds, FlexibleContexts, QuasiQuotes, TemplateHaskell, StandaloneDeriving #-}
-- build-dependency: Frames
import Frames

-- Data set from http://vincentarelbundock.github.io/Rdatasets/datasets.html
tableTypes "Row" "$filename"

-- deriving instance Show Row

readData :: IO (Frame Row)
readData = inCoreAoS (readTable "$filename")

main = readData >>= print
EOF
;;
    elm-package.json) echo json-autotype --no-test -o $outfile $filename
;;
  *) echo "Do not know how to handle $filename of `file --mime-type $filename`"
;;
esac
done;
