#!/bin/bash

for filename in $*; do
  case $(file --mime-type ${filename}) in
    text/plain) cat - <<EOF
import qualified Data.Text

readData = Data.Text.readFile "$i"

main = readData >>= print
EOF
;;
    text/csv) cat - <<EOF
{-# LANGUAGE DataKinds, FlexibleContexts, QuasiQuotes, TemplateHaskell #-}
-- build-dependency: Frames
import Frames

-- Data set from http://vincentarelbundock.github.io/Rdatasets/datasets.html
tableTypes "Row" "$filename"

readData :: IO (Frame Row)
readData = inCoreAoS (readTable "$filename")
EOF
;;
    text/json) cat -<<EOF
{-# LANGUAGE DataKinds, FlexibleContexts, QuasiQuotes, TemplateHaskell #-}
-- build-dependency: Frames
import Frames

-- Data set from http://vincentarelbundock.github.io/Rdatasets/datasets.html
tableTypes "Row" "$filename"

readData :: IO (Frame Row)
readData = inCoreAoS (readTable "$filename")
EOF
;;
  *) echo "Do not know how to handle $filename of `file --mime-type $filename`"
;;
esac > $(basename $filename).hs;
done;
